# Generated by Django 3.2.4 on 2021-11-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='conference',
            field=models.CharField(max_length=450),
        ),
    ]
