# Generated by Django 3.2.4 on 2021-11-16 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_alter_talk_conference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talk',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='talk',
            name='speakers',
            field=models.ManyToManyField(blank=True, related_name='speakers', to=settings.AUTH_USER_MODEL),
        ),
    ]
