# Generated by Django 3.2.4 on 2021-11-16 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conference_app', '0002_conference_talk'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
